# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-02 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=32)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
#因为在models.py创建数据表时忘记设置主键，在这里django自动创建了id属性并设置为主键，自增的整型
#执行pyhton manage.py sqlmigrate 应用名 文件id 查看SQL语句
# ---  eg：python manage.py sqlmigrate blog 0001
#默认sqlite3的数据库在项目根目录的db.sqlite3，使用SQLite Expert Personal打开
#