# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170814_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=40, verbose_name='visitor_name')),
                ('comment_time', models.DateField(verbose_name='comment_time')),
                ('comments', models.TextField(max_length=200, verbose_name='comments')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_id', to='blog.Article')),
            ],
        ),
    ]
